import numpy as np
numbers = [6,2,8,9,3]
print(type(numbers))
array1 = np.array(numbers)
print(type(array1))
print(array1)
arrangednumbers = np.arange(0,len(numbers),1)
print(arrangednumbers)
z1 = np.zeros(5,float)
z2 = np.ones((5,2),int)
print(z1)
print(z2)
print(z1.ndim)
print(z2.ndim)
print(z1.shape)
print(z2.shape)
print(z1.size)
print(z2.size)
z3 = z2.reshape(10)
print(z3)
array2 = np.linspace(10,22,4)
print(array2)
array3 = np.random.randint(0,10,6)
print(array3)
permutation = np.random.permutation(array2)
print(permutation)
